steps:
  # ===== TRAIN =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build train image'
    args: [
      'build',
      '.',
      '-f',
      'dockerfiles/train.dockerfile',
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-train'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push train image'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-train'
    ]

  # ===== API =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build api image'
    args: [
      'build',
      '.',
      '-f',
      'dockerfiles/api.dockerfile',
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-api'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push api image'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-api'
    ]

  # ===== EVALUATE =====
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build evaluate image'
    args: [
      'build',
      '.',
      '-f',
      'dockerfiles/evaluate.dockerfile',
      '-t',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-evaluate'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push evaluate image'
    args: [
      'push',
      'europe-west1-docker.pkg.dev/$PROJECT_ID/container-reg/clickbait-evaluate'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
